# Generated by Django 3.2.6 on 2022-07-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_f_lscd03_tasavcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_LSCD_03',
            fields=[
                ('f_lscd03_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.f_lscd03')),
            ],
            bases=('api.f_lscd03',),
        ),
    ]
