# Generated by Django 3.2.6 on 2022-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
