# Generated by Django 3.2.6 on 2022-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220714_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to=''),
        ),
    ]
